hostname = "${hostname}"

trust_bundle_cert = "file:///var/secrets/root-ca.pem"

[provisioning]
source = "manual"
connection_string = "${connection_string}"

[edge_ca]
cert = "file:///var/secrets/edge-ca.pem"
pk = "file:///var/secrets/edge-ca.key.pem"
